entrega_final/blog_vista/urls.py
from django.urls import path 
from blog_vista import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required




urlpatterns = [
    path('', views.inicio, name='Inicio'),
    path('inicio/', views.InicioView.as_view(), name='inicio'),
    path('about/', views.about, name='About'),
    path('medicina/', login_required(views.medicina), name='Medicina'),
    path('miembros/', login_required(views.miembros), name='Miembros'),
    path('biologia/', login_required(views.biologia), name='Biologia'),
    path('filosofia/', login_required(views.filosofia), name='Filosofia'),
    path('astronomia/', login_required(views.astronomia), name='Astronomia'),
    path('tecnologia/', login_required(views.tecnologia), name='Tecnologia'),
    path('medicina/list', views.MedicinaList.as_view(), name='MedicinaList'),
    path('medicina/detalle/<int:pk>', views.MedicinaDetalle.as_view(), name='MedicinaDetail'),
    path('astronomia/list', views.AstronomiaList.as_view(), name='AstronomiaList'),
    path('astronomia/detalle/<int:pk>', views.detalle_astronomia, name='AstronomiaDetail'),
    path('filosofia/list', views.FilosofiaList.as_view(), name='FilosofiaList'),
    path('filosofia/detalle/<int:pk>', views.detalle_filosofia, name='FilosofiaDetail'),
    path('biologia/list', views.BiologiaList.as_view(), name='BiologiaList'), 
    path('biologia/detalle/<int:pk>', views.detalle_biologia, name='BiologiaDetail'),
    path('tecnologia/list', views.TecnologiaList.as_view(), name='TecnologiaList'),
    path('tecnologia/detalle/<int:pk>', views.detalle_tecnologia, name = 'TecnologiaDetail'),
    path('miembros/list', views.MiembrosList.as_view(), name='MiembrosList'),
    path('miembros/detalle/<int:pk>', views.MiembrosDetalle.as_view(), name='MiembrosDetail'),
    path('miembrosForm', views.miembros_form, name = 'MiembrosForm'),
    path('medicinaForm', views.medicina_form, name ='MedicinaForm' ),
    path('biologiaForm', views.biologia_form, name ='BiologiaForm' ),
    path('astronomiaForm', views.astronomia_form, name ='AstronomiaForm' ),
    path('filosofiaForm', views.filosofia_form, name ='FilosofiaForm' ),
    path('tecnologiaForm', views.tecnologia_form, name ='TecnologiaForm' ),
    path('miembros/editar/<int:pk>', views.MiembrosUpdate.as_view(), name='MiembrosEdit'),
    path('miembros/borrar/<int:pk>', views.MiembrosDelete.as_view(), name='MiembrosDelete'),
    path('medicina/editar/<int:pk>', views.MedicinaUpdate.as_view(), name='MedicinaEdit'),
    path('medicina/borrar/<int:pk>', views.MedicinaDelete.as_view(), name='MedicinaDelete'),
    path('astronomia/editar/<int:pk>', views.AstronomiaUpdate.as_view(), name='AstronomiaEdit'),
    path('astronomia/borrar/<int:pk>', views.AstronomiaDelete.as_view(), name='AstronomiaDelete'),
    path('biologia/editar/<int:pk>', views.BiologiaUpdate.as_view(), name='BiologiaEdit'),
    path('biologia/borrar/<int:pk>', views.BiologiaDelete.as_view(), name='BiologiaDelete'),
    path('filosofia/editar/<int:pk>', views.FilosofiaUpdate.as_view(), name='FilosofiaEdit'),
    path('filosofia/borrar/<int:pk>', views.FilosofiaDelete.as_view(), name='FilosofiaDelete'),
    path('tecnologia/editar/<int:pk>', views.TecnologiaUpdate.as_view(), name='TecnologiaEdit'),
    path('tecnologia/borrar/<int:pk>', views.TecnologiaDelete.as_view(), name='TecnologiaDelete'),
    path('login',views.login_request, name="Login"),
    path('register', views.register, name='Register'),
    path('logout', LogoutView.as_view(template_name='blog_vista/logout.html'), name='Logout'),
    path('editarPerfil', views.editarPerfil, name="EditarPerfil"),
    path('profile', login_required(views.profile), name='Profile'),
    path('inicio_login', login_required(views.inicio_login), name = 'InicioLogin'),
    path('agregarAvatar', views.agregarAvatar, name="AgregarAvatar"),

]




    

entrega_final/entrega_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog_vista/', include('blog_vista.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entrega_final/blog_vista/models.py
from django.db import models
from django.contrib.auth.models import User

class Medicina (models.Model):

    titulo = models.CharField(max_length = 30)
    subtitulo = models.CharField(max_length = 50)
    texto = models.CharField(max_length = 4000)
    autor =  models.CharField(max_length = 30)
    fecha = models.DateField(auto_now_add=True)
    imagen = models.ImageField(upload_to='media', null=True, blank = True)
    def __str__ (self):
        return f'Titulo: {self.titulo} | Autor: {self.autor} | Fecha: {self.fecha}'

class Biología (models.Model): 

    titulo = models.CharField(max_length = 30)
    subtitulo = models.CharField(max_length = 50)
    texto = models.CharField(max_length = 4000)
    autor =  models.CharField(max_length = 30)
    fecha = models.DateField(auto_now_add=True)
    imagen = models.ImageField(upload_to='media', null=True, blank = True)    
    def __str__ (self):
        return f'Titulo: {self.titulo} | Autor: {self.autor} | Fecha: {self.fecha}'

class Filosofía (models.Model): 

    titulo = models.CharField(max_length = 30)
    subtitulo = models.CharField(max_length = 50)
    texto = models.CharField(max_length = 4000)
    autor =  models.CharField(max_length = 30)
    fecha = models.DateField(auto_now_add=True)
    imagen = models.ImageField(upload_to='media', null=True, blank = True)
    def __str__ (self):
        return f'Titulo: {self.titulo} | Autor: {self.autor} | Fecha: {self.fecha}'

class Astronomía (models.Model): 

    titulo = models.CharField(max_length = 30)
    subtitulo = models.CharField(max_length = 50)
    texto = models.CharField(max_length = 4000)
    autor =  models.CharField(max_length = 30)
    fecha = models.DateField(auto_now_add=True)
    imagen = models.ImageField(upload_to='media', null=True, blank = True)
    def __str__ (self):
        return f'Titulo: {self.titulo} | Autor: {self.autor} | Fecha: {self.fecha}'

class Tecnología (models.Model): 

    titulo = models.CharField(max_length = 30)
    subtitulo = models.CharField(max_length = 50)
    texto = models.CharField(max_length = 4000)
    autor =  models.CharField(max_length = 30)
    fecha = models.DateField(auto_now_add=True)
    imagen = models.ImageField(upload_to='media', null=True, blank = True)
    def __str__ (self):
        return f'Titulo: {self.titulo} | Autor: {self.autor} | Fecha: {self.fecha}'

class Miembros (models.Model):

    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField()
    universidad = models.CharField(max_length=30)
    foto = models.ImageField(upload_to='media', null=True, blank = True)
    def __str__ (self):
        return f'Nombre: {self.nombre} | Apellido: {self.apellido} | Email: {self.email}'
    
class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank = True)
    def __str__(self):
        return f"{self.user} - {self.imagen}"

entrega_final/blog_vista/views.py
from django.shortcuts import render
from blog_vista.models import *
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

#vistas principales de los models
from django.templatetags.static import static

def my_view(request):
    background_image_url = static('blog_vista/assets/img/home-bg.jpg')
    return render(request, 'padre.html', {'background_image_url': background_image_url})

def inicio(request):  
    return render (request, 'blog_vista/inicio.html')

def about(request):
    return render (request, 'blog_vista/about.html')
login_required
def medicina(request):
    return render (request, 'blog_vista/medicina.html') 
login_required
def biologia (request):
    return render (request, 'blog_vista/biologia.html')
login_required
def filosofia (request):
    return render (request, 'blog_vista/filosofia.html')
login_required
def astronomia(request):
    return render (request, 'blog_vista/astronomia.html')
login_required
def tecnologia (request):
    return render (request, 'blog_vista/tecnologia.html')
login_required
def miembros (request):
    return render (request, 'blog_vista/miembros.html')




#vistas en listas y detalles de cada model
from django.views.generic import ListView
from django.views.generic.detail import DetailView

class MedicinaList(ListView):
    model = Medicina 
    template_name='/blog_vista/medicina_list.html'

class AstronomiaList(ListView):
    model = Astronomía
    template_name = 'blog_vista/astronomia_list.html'

class FilosofiaList(ListView):
    model = Filosofía
    template_name = 'blog_vista/filosofia_list.html'


class MedicinaDetalle(DetailView):
    model= Medicina
    template_name= "blog_vista/medicina_detalle.html"


def detalle_astronomia(request, pk):

    astronomia = Astronomía.objects.get(pk=pk)
    contexto = {'astronomia': astronomia}
    return render(request, 'blog_vista/astronomia_detalle.html', contexto)

def detalle_filosofia(request, pk):
    filosofia = Filosofía.objects.get(pk=pk)
    contexto = {'filosofia': filosofia}
    return render(request, 'blog_vista/filosofia_detalle.html', contexto)

class BiologiaList(ListView):
    model = Biología
    template_name = 'blog_vista/biologia_list.html'

def detalle_biologia(request, pk):
    biologia = Biología.objects.get(pk=pk)
    contexto = {'biologia': biologia}
    return render(request, 'blog_vista/biologia_detalle.html', contexto)

class TecnologiaList(ListView):
    model = Tecnología
    template_name = 'blog_vista/tecnologia_list.html'


def detalle_tecnologia(request, pk):
    tecnologia = Tecnología.objects.get(pk=pk)
    contexto = {'tecnologia': tecnologia}
    return render(request, 'blog_vista/tecnologia_detalle.html', contexto)

class MiembrosList(ListView):
    model = Miembros
    template_name = 'blog_vista/miembros_list.html'


class MiembrosDetalle(DetailView):
    model = Miembros
    template_name = 'blog_vista/miembros_detalle.html'

#vistas de los forms: 
from django import forms
from .forms import *

from django.contrib.admin.views.decorators import staff_member_required

@staff_member_required
def miembros_form(request): 
    if request.method == 'POST':
        #form = MiembrosForm(request.POST)
        form = MiembrosForm(request.POST, request.FILES)

        if form.is_valid(): 
            informacion = form.cleaned_data
            miembro = Miembros(nombre=informacion['nombre'], apellido=informacion['apellido'], email=informacion['email'], universidad=informacion['universidad'], foto=informacion['foto'])
            miembro.save()
            return render(request, 'blog_vista/inicio.html')
        else:
            print(form.errors)
    
    else:
        form = MiembrosForm()
        
    return render(request, 'blog_vista/miembros_form.html', {'form': form})

@staff_member_required
def medicina_form(request): 
    if request.method == 'POST':
        form = MedicinaForm(request.POST, request.FILES)

        if form.is_valid(): 
            informacion = form.cleaned_data
            articulo_medicina = Medicina(titulo=informacion['titulo'], subtitulo=informacion['subtitulo'], texto=informacion['texto'], autor=informacion['autor'], imagen=informacion['imagen'])
            articulo_medicina.save()
            return render(request, 'blog_vista/inicio.html')
        else:
            print(form.errors)
    
    else:
        form = MedicinaForm()
        
    return render(request, 'blog_vista/medicina_form.html', {'form': form})

@staff_member_required
def filosofia_form(request): 
    if request.method == 'POST':
        form = FilosofiaForm(request.POST, request.FILES)

        if form.is_valid(): 
            informacion = form.cleaned_data
            articulo_filosofia = Filosofía(titulo=informacion['titulo'], subtitulo=informacion['subtitulo'], texto=informacion['texto'], autor=informacion['autor'], imagen=informacion['imagen'])
            articulo_filosofia.save()
            return render(request, 'blog_vista/inicio.html')
        else:
            print(form.errors)
    
    else:
        form = FilosofiaForm()
        
    return render(request, 'blog_vista/filosofía_form.html', {'form': form})

@staff_member_required
def biologia_form(request): 
    if request.method == 'POST':
        form = BiologiaForm(request.POST, request.FILES)

        if form.is_valid(): 
            informacion = form.cleaned_data
            articulo_biologia = Biología(titulo=informacion['titulo'], subtitulo=informacion['subtitulo'], texto=informacion['texto'], autor=informacion['autor'], imagen=informacion['imagen'])
            articulo_biologia.save()
            return render(request, 'blog_vista/inicio.html')
        else:
            print(form.errors)
    
    else:
        form = BiologiaForm()
        
    return render(request, 'blog_vista/biología_form.html', {'form': form})

@staff_member_required
def astronomia_form(request): 
    if request.method == 'POST':
        form = AstronomiaForm(request.POST, request.FILES)

        if form.is_valid(): 
            informacion = form.cleaned_data
            articulo_astronomia = Astronomía(titulo=informacion['titulo'], subtitulo=informacion['subtitulo'], texto=informacion['texto'], autor=informacion['autor'], imagen=informacion['imagen'])
            articulo_astronomia.save()
            return render(request, 'blog_vista/inicio.html')
        else:
            print(form.errors)
    
    else:
        form = AstronomiaForm()
        
    return render(request, 'blog_vista/astronomía_form.html', {'form': form})

@staff_member_required
def tecnologia_form(request): 

    if request.method == 'POST':
        form = TecnologiaForm(request.POST, request.FILES)

        if form.is_valid(): 
            informacion = form.cleaned_data
            articulo_tecnologia = Tecnología(titulo=informacion['titulo'], subtitulo=informacion['subtitulo'], texto=informacion['texto'], autor=informacion['autor'], imagen=informacion['imagen'])
            articulo_tecnologia.save()
            return render(request, 'blog_vista/inicio.html')
        else:
            print(form.errors)
    
    else:
        form = TecnologiaForm()
        
    return render(request, 'blog_vista/tecnología_form.html', {'form': form})

#vistas de edicion

from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator

class InicioView(TemplateView):
    template_name = 'blog_vista/inicio.html'

def user_is_admin(user):
    return user.is_superuser

@method_decorator(staff_member_required, name='dispatch')
class MiembrosUpdate(UpdateView):
    model = Miembros
    success_url = reverse_lazy('MiembrosList')
    fields = ['nombre', 'apellido', 'email', 'universidad', 'foto']

@method_decorator(staff_member_required, name='dispatch')
class MiembrosDelete(DeleteView):
    model = Miembros
    success_url = reverse_lazy('MiembrosList')

@method_decorator(staff_member_required, name='dispatch')
class AstronomiaUpdate(UpdateView):
    model = Astronomía
    success_url = reverse_lazy('AstronomiaList')
    fields = ['titulo', 'subtitulo', 'texto', 'autor', 'imagen']

@method_decorator(staff_member_required, name='dispatch')
class AstronomiaDelete(DeleteView):
    model = Astronomía
    success_url = reverse_lazy('AstronomiaList')

@method_decorator(staff_member_required, name='dispatch')
class BiologiaUpdate(UpdateView):
    model = Biología
    success_url = reverse_lazy('BiologiaList')
    fields = ['titulo', 'subtitulo', 'texto', 'autor', 'imagen']

@method_decorator(staff_member_required, name='dispatch')
class BiologiaDelete(DeleteView):
    model = Biología
    success_url = reverse_lazy('BiologiaList')

@method_decorator(staff_member_required, name='dispatch')
class MedicinaUpdate(UpdateView):
    model = Medicina
    success_url = reverse_lazy('MedicinaList')
    fields = ['titulo', 'subtitulo', 'texto', 'autor', 'imagen']

@method_decorator(staff_member_required, name='dispatch')
class MedicinaDelete(DeleteView):
    model = Medicina
    success_url = reverse_lazy('MedicinaList')

@method_decorator(staff_member_required, name='dispatch')
class FilosofiaUpdate(UpdateView):
    model = Filosofía
    success_url = reverse_lazy('FilosofiaList')
    fields = ['titulo', 'subtitulo', 'texto', 'autor', 'imagen']

@method_decorator(staff_member_required, name='dispatch')
class FilosofiaDelete(DeleteView):
    model = Filosofía
    success_url = reverse_lazy('FilosofiaList')

@method_decorator(staff_member_required, name='dispatch')
class TecnologiaUpdate(UpdateView):
    model = Tecnología
    success_url = reverse_lazy('TecnologiaList')
    fields = ['titulo', 'subtitulo', 'texto', 'autor', 'imagen']

@method_decorator(staff_member_required, name='dispatch')
class TecnologiaDelete(DeleteView):
    model = Tecnología

entrega_final/blog_vista/templates/blog_vista/astronomia_detalle.html
{% extends 'blog_vista/padre.html' %}
{% load static %}

{% block astronomia %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{astronomia.titulo}}</title>
</head>
<div class="container text-center"> 
    <body>
        <img style="height:150px" src="{{ astronomia.imagen.url }}" alt="Imagen">
        <p><h1> <i>{{ astronomia.titulo }}</i></p></h1>
        <p><h2><i>{{ astronomia.subtitulo }}</i></p></h2>
        <p>Por: <i>{{ astronomia.autor }}</i></p>
        <p>Fecha: <i>{{ astronomia.fecha }}</i></p>
        <p><i>{{ astronomia.texto }}</i></p>
        
        <p>
            <a class="btn btn-primary" href="{% url 'AstronomiaList' %}">Regresar</a>
        </p>
    </body>
</div>
</html>

{%endblock%}

entrega_final/blog_vista/templates/blog_vista/astronomia_form.html
{% extends 'blog_vista/padre.html' %}
{% load static %}
{% block astronomia %}


                <form enctype="multipart/form-data" action = "" method = 'POST'> 
                    
                    {%csrf_token%}
                    
                    <table>

                        {{formulario.as_table}}

                    </table>
                    
                     
                    <input type="submit" value="Enviar">
                </form>

{%endblock%}   

entrega_final/blog_vista/templates/blog_vista/biologia_detalle.html
{% extends 'blog_vista/padre.html' %}
{% load static %}

{% block biologia %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ biologia.titulo }}</title>
</head>
<div class="container text-center">
    <body>
        
        <img style="height:150px" src="{{ biologia.imagen.url }}" alt="Imagen">
        
        <p><h1> <i>{{ biologia.titulo }}</i></p></h1>
        <p><h2><i>{{ biologia.subtitulo }}</i></p></h2>
        <p>Por: <i>{{ biologia.autor }}</i></p>
        <p>Fecha: <i>{{ biologia.fecha }}</i></p>
        <p><i>{{ biologia.texto }}</i></p>
        
        <p>
            <a class="btn btn-primary" href="{% url 'BiologiaList' %}">Regresar</a>
        </p>
    </body>
</div>
</html>
{% endblock %}

entrega_final/blog_vista/templates/blog_vista/biología_confirm_delete.html
{% extends 'blog_vista/padre.html' %}
{% load static %}

{% block biologia %}
<div class="container text-center">
    <body>
        
        <form method="post">{% csrf_token %}
            ¿Estas seguro de que deseas borrar a este articulo? <br>"{{ object }}"?<br>
            <input type="submit" value="Borrar">
        </form>
    </body>
    <a class="btn btn-primary" href="{% url 'BiologiaList' %}">Regresar</a>
</div>
{% endblock %}

entrega_final/blog_vista/templates/blog_vista/filosofia_detail.html
{% extends 'blog_vista/padre.html' %}
{% load static %}

{% block filosofia %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{filosofia.titulo}}</title>
</head>
<body>
    <p><i>{{ filosofia.imagen }}</i></p>
    <p>Titulo: <i>{{ filosofia.titulo }}</i></p>
    <p>Subtitulo: <i>{{ filosofia.subtitulo }}</i></p>
    <p>Autor: <i>{{ filosofia.autor }}</i></p>
    <p>Fecha: <i>{{ filosofia.fecha }}</i></p>
    <p>Texto: <i>{{ filosofia.texto }}</i></p>
    
    <p>
        <a class="btn btn-primary" href="{% url 'FilosofiaList' %}">Regresar</a>
    </p>
</body>
</html>

{%endblock%}

entrega_final/blog_vista/templates/blog_vista/filosofía_confirm_delete.html
{% extends 'blog_vista/padre.html' %}
{% load static %}

{% block filosofia %}
<div class="container text-center">
    <body>
        
        <form method="post">{% csrf_token %}
            ¿Estas seguro de que deseas borrar a este articulo? <br>"{{ object }}"?<br>
            <input type="submit" value="Borrar">
        </form>
        <a class="btn btn-primary" href="{% url 'FilosofiaList' %}">Regresar</a>
    </body>
</div>

{% endblock %}

entrega_final/blog_vista/templates/blog_vista/inicio.html
{% extends 'blog_vista/padre.html' %}
{% load static %}
{% block inicio %}



<!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    {% if mensaje %}
        <p>{{ mensaje }}</p>
    {% endif %}


{%endblock%}

entrega_final/blog_vista/templates/blog_vista/medicina_confirm_delete.html
{% extends 'blog_vista/padre.html' %}
{% load static %}

{% block medicina %}
<div class="container text-center">
<body>
    
    <form method="post">{% csrf_token %}
        ¿Estas seguro de que deseas borrar a este articulo? <br>"{{ object }}"?<br>
        <input type="submit" value="Borrar">
    </form>
    <a class="btn btn-primary" href="{% url 'MedicinaList' %}">Regresar</a>
</body>
</div>
{% endblock %}

entrega_final/blog_vista/templates/blog_vista/medicina_detalle.html
{% extends 'blog_vista/padre.html' %}
{% load static %}

{% block medicina %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{medicina.titulo}}</title>
</head>
<div class="container text-center">
<body>
    <img style="height:150px" src="{{ medicina.imagen.url }}" alt="Imagen">

    <p><h1> <i>{{ medicina.titulo }}</i></p></h1>
    <p><h2><i>{{ medicina.subtitulo }}</i></p></h2>
    <p>Por: <i>{{ medicina.autor }}</i></p>
    <p>Fecha: <i>{{ medicina.fecha }}</i></p>
    <p><i>{{ medicina.texto }}</i></p>
    
    <p>
        <a class="btn btn-primary" href="{% url 'MedicinaList' %}">Regresar</a>
    </p>
</body>
</div>
</html>

{%endblock%}

entrega_final/blog_vista/templates/blog_vista/miembros_detalle.html
{% extends 'blog_vista/padre.html' %}
{% load static %}

{% block miembros %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{miembros.nombre}}</title>
</head>
<div class="container text-center"> 
<body>
    
    <img style="height:150px" src="{{ miembros.foto.url }}" alt="Imagen">
    
    
    <p>Nombre: <i>{{ miembros.nombre }}</i></p>
    <p>Apellido: <i>{{ miembros.apellido }}</i></p>
    <p>Email: <i>{{ miembros.email }}</i></p>

    <p>
        <a class="btn btn-primary" href="{% url 'MiembrosList' %}">Regresar</a>
    </p>
</body>
</div>
</html>

{%endblock%}

entrega_final/blog_vista/templates/blog_vista/profile.html
{% extends "blog_vista/padre.html" %}
{% load static %}
{% block inicio %}
   
<div class="container text-center">
    <h1></h1>
    <h1> Perfil De {{usuario}}</h1>
    
        
        
            <li>
                {% if request.user.is_authenticated %}
                    {% with avatares=request.user.avatar_set.all %}
                        {% if avatares %}
                            <img height = '100px' src = '{{avatares.0.imagen.url}}'>
                        {% endif %}
                
                    {% endwith %}
                {% endif %}
                <p>email: {{ usuario.email }}</p>
                <p>Nombre: {{ usuario.first_name}}</p>
                <p>Apellido: {{ usuario.last_name }}</p>

            </li>
</div>
       
     
{% endblock %}

entrega_final/blog_vista/templates/blog_vista/tecnologia_detalle.html
{% extends 'blog_vista/padre.html' %}
{% load static %}

{% block tecnologia %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{tecnologia.titulo}}</title>
</head>
<div class="container text-center"> 
<body>
    
        <img style="height:150px" src="{{ tecnologia.imagen.url }}" alt="">
    
        <p><h1> <i>{{ tecnologia.titulo }}</i></p></h1>
        <p><h2><i>{{ tecnologia.subtitulo }}</i></p></h2>
        <p>Por: <i>{{ tecnologia.autor }}</i></p>
        <p>Fecha: <i>{{ tecnologia.fecha }}</i></p>
        <p><i>{{ tecnologia.texto }}</i></p>
    
    <p>
        <a class="btn btn-primary" href="{% url 'TecnologiaList' %}">Regresar</a>
    </p>
</body>
</div>
</html>

{%endblock%}

entrega_final/blog_vista/templates/blog_vista/tecnologia_list.html
{% extends 'blog_vista/padre.html' %}
{% load static %}

{% block tecnologia %}

<body>
    <h1>Articulos de Tecnologia</h1>
    <ul>
        {% for tecnologia in object_list %}
            <li>
                <p>Titulo: {{ tecnologia.titulo }}</p>
                <p>Autor: {{ tecnologia.autor }}</p>
                <p>Fecha: {{ tecnologia.fecha }}</p>
                
                <p>
                    <a href="{% url 'TecnologiaDetail' tecnologia.id %}">Leer más</a>
                    <a href="{% url 'TecnologiaEdit' tecnologia.id %}">Editar articulo</a>
                    <a href="{% url 'TecnologiaDelete' tecnologia.id %}">Borrar articulo</a>
                </p>
            </li>
        {% endfor %}
    </ul>
    
</body>

{% endblock %}

entrega_final/blog_vista/templates/blog_vista/tecnología_form.html
{% extends 'blog_vista/padre.html' %}
{% load static %}
{% block tecnologia %}

<div class="container text-center"> 
                <form enctype="multipart/form-data" action = "" method = 'POST'> 
                    
                    {%csrf_token%}
                    
                    <table>

                        {{form.as_table}}

                    </table>
                    
                     
                    <input type="submit" value="Enviar">
                </form>
                <a class="btn btn-primary" href="{% url 'TecnologiaList' %}">Regresar</a>
</div>
{%endblock%}   